### ISSUE TITLE
주사위 게임 3

### ISSUE THREAD

**Issue by key262yek** [heidi505/Programmers#1]
1. [line 29](https://github.com/heidi505/Programmers/blob/a4e8dffa6289f2e9cc216e71e970540a0fff35c9/src/main/java/Logic.java#L29) Index 문제
    - `arr[0] * arr[1]`이 되어야 함. 

2. 불필요한 else if가 많음. If 문은 computing cost가 큰 구문이고, 또한 너무 복잡하면 가독성을 떨어뜨리기 때문에 최대한 간소화 하는 것이 좋음. 
    - 잘 정리하면  [line 33](https://github.com/heidi505/Programmers/blob/a4e8dffa6289f2e9cc216e71e970540a0fff35c9/src/main/java/Logic.java#L33) 새로운 if문을 쓸 필요가 없을것

**Comment by heidi505** [comment]
감사합니다,,,,ㅠㅠ
